### ISSUE TITLE
SQL server logstore

### ISSUE THREAD

**Issue by opoani** [lowleveldesign/diagnostics-kit#2]
Hi, first thanks for sharing some great work!

Have you already implemented an sql server log store or whats the case there ?
The documentation talks about this briefly in section 3.1 "Log stores using ElasticSearch, MySql or SQL Server support " But in the repository i cant find anything beside mysql.

Many thanks //Anders

**Comment by lowleveldesign** [comment]
Hi Anders,

Thank you for your message :) I hope we will be able to make DiagnosticsKit work for you.

As far as SQL Server is concerned I had a plan to add a support for it, but unfortunately run out of time :( The very basic support would not be difficult to implement (all the code is almost ready in the default provider (LogStores\LowLevelDesign.Diagnostics.LogStore.Defaults\). However if we store all the logs in one table, the maintenance performance might be really bad. Solution to this problem is usually table partitioning, which is available in SQL Server Ultimate and not many people run this version of SQL Server. That's why I focused on MySql which gives partitioning for free. 

So the question is: are you running a Sql Server Standard or Ultimate? And if Standard how many logs would you like to store in a table (or in other words: would 'delete from' be feasible)?

**Comment by opoani** [comment]
No worries i totally understand the time aspect, so no stress there. I am just investigating the capabilities of diagnostic-kit and if sql-server is not available then we could consider using another log-store but since sql-server is our main db solution it would be preferable to use that.  
 
when it comes to sql server then we are running standard edition and delete to purge the logs is not a problem as i see it. The amount of records logged would be in the range of 2 weeks as of time-frame and about 20 different apps will write to logs. Each app will roughly write  maximum a few hundred entries per day is my rough estimate. 

So the need for partitioning the data in our case is very low since the amount of info we want to log and store is very limited.  The main use case  we want fulfill is to use diagnostic-kit as an overview of completed and failed operations more than logging everything that is happening all the time.  

The initial idea is to have a separate log4net adapter that can be picked up by the harvester , more detailed logging could be processed in our normal way of logging. The main purpose is to test if diagnostics-kit can serve as a dashboard to see whats "up/down" and do we have any failing operations that need attention.

**Comment by lowleveldesign** [comment]
In that case I'm keeping this issue open and I will try to implement the basic (one-table for logs) SQL Server support in the nearest feature. Will let you know when it happens :)

**Comment by lowleveldesign** [comment]
Hi @opoani, SQL Server is now supported (version 1.1). More in wiki: https://github.com/lowleveldesign/diagnostics-kit/wiki/3.4.log-store-sql-server

**Comment by opoani** [comment]
Many thanks Sebastian ,

I will check this out and give feedback.


Från: Sebastian Solnica [mailto:notifications@github.com]
Skickat: den 30 juli 2016 17:18
Till: lowleveldesign/diagnostics-kit <diagnostics-kit@noreply.github.com>
Kopia: Anders Nilsson <Anders.Nilsson@soderbergpartners.se>; Mention <mention@noreply.github.com>
Ämne: Re: [lowleveldesign/diagnostics-kit] SQL server logstore (#2)


Hi @opoani<https://github.com/opoani>, SQL Server is now supported (version 1.1). More in wiki: https://github.com/lowleveldesign/diagnostics-kit/wiki/3.4.log-store-sql-server
